AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - tmp/**/*
    - db/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120
