default: &default
  adapter: postgresql
  encoding: utf8
  username: michi
  password:
  host: 127.0.0.1
  port: 5434

development:
  <<: *default
  database: development_expenses

test:
  <<: *default
  database: test_expenses

production:
  <<: *default
  database: production_expenses
